### ISSUE TITLE
Scoped Atlassian Tokens Break Relative Links to Other Pages in Directory Mode

### ISSUE THREAD

**Issue by Virdir29** [hunyadi/md2conf#121]
---
Scoped Atlassian Tokens Break Relative Links to Other Pages in Directory Mode
---

First off, thank you for this phenomenal library! The upgrade to v2 endpoints and the ongoing improvements are greatly appreciated, and have made documentation automation with Confluence much more robust.

## 🐞 Bug: Scoped Tokens Break Relative Links in Directory Mode

As Atlassian is deprecating general (unscoped) API tokens in favor of more secure [scoped API tokens](https://community.atlassian.com/forums/Confluence-questions/Scoped-API-Token-returns-Unauthorized-for-simple-query/qaq-p/3023662), many of us are transitioning to the new authentication model:

> **API tokens without scopes are being deprecated. We encourage creating the more secure API tokens with scopes whenever possible.**

When using scoped tokens, the API endpoint must be constructed differently as outlined in the [Atlassian OAuth documentation](https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/#3-2-construct-the-request-url):

#### For example:
```yaml
CONFLUENCE_DOMAIN: api.atlassian.com/ex/confluence
CONFLUENCE_PATH: /{Cloud_Id}/

instead of:

CONFLUENCE_DOMAIN: example.atlassian.net
CONFLUENCE_PATH: /wiki/

My alteration using GitHub Actions:

- name: Publish Documentation to Confluence
  env:
    CONFLUENCE_DOMAIN: api.atlassian.com/ex/confluence
    CONFLUENCE_PATH: /{Cloud_Id}/
    CONFLUENCE_USER_NAME: {Email}
    CONFLUENCE_API_KEY: ${{ secrets.CONFLUENCE_SCOPED_API_TOKEN }}  
    CONFLUENCE_SPACE_KEY: {Space_Key}
  run: |
    python3 -m md2conf docs \
      -r <CONFLUENCE_ROOT_PAGE_ID> \
      --no-render-mermaid \
      --keep-hierarchy \
      --heading-anchors \
      --generated-by "Do not edit! This page is automatically generated by GitHub Actions."
```

## ❗ Problem

When using scoped tokens, **generated links between pages** (for example, relative links to other Markdown files in the same directory) are constructed using the API base URL:

```
https://api.atlassian.com/ex/confluence/{CloudId}/spaces/{SpaceKey}/pages/{PageId}/
```

However, this is **not a valid browser-visible link** for Confluence users, and such URLs do not resolve to the actual page in the web UI. This breaks a very useful feature of `md2conf`—maintaining local links between documentation pages.

With general (unscoped) tokens, links are generated like:

```
https://example.atlassian.net/wiki/spaces/{SpaceKey}/pages/{PageId}/
```

which works as expected in the Confluence web UI.

## 💡 Proposed Solution

It would be great if `md2conf` could distinguish between API endpoint usage (which requires the new scoped token endpoints) and the generation of user-facing links (which should always use the classic Confluence domain and `/wiki/` path).

For example:

- Use `api.atlassian.com/ex/confluence/{cloudId}/...` for API calls
- But continue to generate internal page links as `https://example.atlassian.net/wiki/spaces/{SpaceKey}/pages/{PageId}/` for user-facing documentation

This would ensure that local links between pages remain functional and user-friendly, even as we transition to the more secure, scoped token model that Atlassian is enforcing.

## 🙏 Thanks!

Thank you so much for your hard work on this project. I wanted to bring this to your attention as Atlassian is deprecating general tokens, and many users may run into this issue.

**References:**

- [Scoped API Token Unauthorized Issue](https://community.atlassian.com/forums/Confluence-questions/Scoped-API-Token-returns-Unauthorized-for-simple-query/qaq-p/3023662)
- [Atlassian OAuth 2.0 Request URL Construction](https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/#3-2-construct-the-request-url)

**Comment by hunyadi** [comment]
Thank you for such a detailed and specific issue report!

I have yet to go through Atlassian documentation in depth but it appears we will need to introduce a new environment variable (and corresponding command-line parameter) `CONFLUENCE_API` in addition to `CONFLUENCE_DOMAIN`. `CONFLUENCE_DOMAIN` and `CONFLUENCE_PATH` would be used for constructing links in documents, and `CONFLUENCE_API` would be used for accessing the REST API.

What we need to look into if there is a programmatic method to determine `CONFLUENCE_DOMAIN` and `CONFLUENCE_PATH` if the user has passed `CONFLUENCE_API` such that users have to set fewer parameters.

**Comment by Virdir29** [comment]
Thank you for the incredibly quick turnaround and for implementing the new `CONFLUENCE_API_URL` environment variable and `--api-url` CLI option! I tested the latest changes from the `master` branch using the following GitHub Actions workflow, and I can confirm that **relative links between Markdown files now work as expected** when publishing with scoped API tokens:

```yaml
name: Sync Markdown to Confluence (Python CLI)

on:
  push:
    branches: [main]
    # Trigger workflow on any relevant change to documentation in main branch 
    paths:
      - 'sampleDocs/**/*.md'
      - 'sampleDocs/**/*.png'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'

      - name: Install markdown-to-confluence from GitHub main branch
        run: pip install git+https://github.com/hunyadi/md2conf.git@master

      - name: Publish Documentation to Confluence
        env:
          CONFLUENCE_API_URL: https://api.atlassian.com/ex/confluence/{Cloud_Id}/
          CONFLUENCE_DOMAIN: example-company.atlassian.net
          CONFLUENCE_PATH: /wiki/
          CONFLUENCE_USER_NAME: {Email}
          CONFLUENCE_API_KEY: ${{ secrets.CONFLUENCE_SCOPED_API_TOKEN }}  
          CONFLUENCE_SPACE_KEY: {Space_Key}
        run: |
          python3 -m md2conf sampleDocs \
            -r <CONFLUENCE_ROOT_PAGE_ID> \
            --no-render-mermaid \
            --heading-anchors \
            --generated-by "Do not edit! This page is automatically generated by GitHub Actions."
```

---

### On Programmatic Determination of `CONFLUENCE_DOMAIN` and `CONFLUENCE_PATH`

Regarding the ability to programmatically determine `CONFLUENCE_DOMAIN` and `CONFLUENCE_PATH` if the user has supplied only `CONFLUENCE_API_URL`, here’s what I’ve found:

- If users are utilizing the scoped API token endpoint constructed as follows:
  ```
  https://api.atlassian.com/ex/confluence/{cloudId}/...
  ```
  you are correct that the base domain and path for the Confluence instance can be obtained programmatically.

- This can be done by making a simple API call:
  ```bash
  curl --request GET \
    --url 'https://api.atlassian.com/ex/confluence/{Cloud-ID}/api/v2/spaces?limit=1' \
    --user '<email>:<api-token>' \
    --header 'Accept: application/json' | jq -r '._links.base'
  ```
  [Reference: Atlassian REST API v2 - Get spaces](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-space/#api-spaces-get)

- The response will include a `base` field (e.g., `https://example-company.atlassian.net/wiki`), from which both the `CONFLUENCE_DOMAIN` and `CONFLUENCE_PATH` can be determined programmatically. This means users only need to supply `CONFLUENCE_API_URL`, and your tool can extract the rest as needed.

- Additionally for reference, I skimmed the source code for *md2conf* and, cross-referencing the Atlassian v2 api documentation, I believe the minimum required scopes for scoped api tokens using the tool are:

  - `read:page:confluence`
  - `write:page:confluence`
  - `read:space:confluence`
  - `write:space:confluence`
  - `read:attachment:confluence`
  - `write:attachment:confluence`
  - `read:label:confluence`
  - `write:label:confluence`

In my token, however, I also include the following additional scopes (since I use the token with other automation workflows): 
  - `search:confluence`
  - `delete:page:confluence`
  - `read:content-details:confluence`
  - `write:content.property:confluence`

which may or may not be required just in case other users try to set up a scoped api token to work with *md2conf*.



Personally, I don't mind passing the extra parameter, but the above approach should make endpoint detection fully automatic if you wish to implement it.

Thanks again for your rapid support and for the library!
